env:
  es6: true
  jest: true
  node: true
parserOptions:
  ecmaVersion: 9
  sourceType: module
extends:
  - eslint:recommended
  - plugin:prettier/recommended
rules:
  prettier/prettier:
    - error
